### ISSUE TITLE
this.db.settings({ timestampsInSnapshots: true }) is now the default in firestore

### ISSUE THREAD

**Issue by evdama** [the-road-to-react-with-firebase/react-firestore-authentication#11]
` this.db.settings({ timestampsInSnapshots: true });` is now the **default in firestore** and therefore the setting is unnecessary and throws an error.

**Comment by rwieruch** [comment]
Can you open a PR to fix it? :)

**Comment by evdama** [comment]
done, have a look, guck mal hin ;)
https://github.com/the-road-to-react-with-firebase/react-firestore-authentication/pulls

**Comment by rwieruch** [comment]
Thank you! :) 🎉
