### ISSUE TITLE
Sign-up: "A continue URL must be provided in the request."

### ISSUE THREAD

**Issue by Speekless** [the-road-to-react-with-firebase/react-firestore-authentication#5]
I've adapted the project in your online tutorial with these files.  User is created in Firebase, as is the firestore collection, but I get "A continue URL must be provided in the request." on signup.

**Comment by Speekless** [comment]
My bad, needed to set the .env variable.

**Comment by symmetriccurve** [comment]
For those who could not get this resolved: 
Creating a .env file on the root of the project and adding 
`REACT_APP_CONFIRMATION_EMAIL_REDIRECT=http://localhost:3000` should resolve the issue, assuming the port on which the application is running is `3000`

[Reference](https://github.com/the-road-to-react-with-firebase/react-firestore-authentication/blob/master/README.md#firebase-configuration)
